 .env.example                     |   7 [32m+[m
 .github/workflows/deploy.yml     |   2 [32m+[m[31m-[m
 attendance_manager.py            |  64 [32m++++[m[31m-[m
 check_db.py                      |   8 [32m+[m[31m-[m
 deploy/DEPLOYMENT.md             |   3 [32m+[m
 main_with_face_recognition.py    | 493 [32m+++++++++++++++++++++++++++++++++++++[m[31m--[m
 migrate_phase6.py                | 142 [32m+++++++++++[m
 reports.py                       | 102 [32m++++++[m[31m--[m
 send_daily_nudge.py              | 223 [32m++++++++++++++++++[m
 templates/attendance.html        |  68 [32m+++++[m[31m-[m
 templates/batches.html           |  13 [32m++[m
 templates/dashboard.html         |   2 [32m+[m[31m-[m
 templates/privacy.html           |  99 [32m++++++++[m
 templates/student.html           | 141 [32m++++++++++[m[31m-[m
 templates/teacher.html           | 181 [32m+++++++++++++[m[31m-[m
 tests/conftest.py                |  24 [32m+[m[31m-[m
 tests/test_endpoint_auth.py      |   3 [32m+[m
 tests/test_half_day.py           | 175 [32m++++++++++++++[m
 tests/test_subjects_timetable.py | 218 [32m+++++++++++++++++[m
 tests/test_working_days.py       | 133 [32m+++++++++++[m
 timetable.py                     | 255 [32m++++++++++++++++++++[m
 working_days.py                  |  83 [32m+++++++[m
 22 files changed, 2373 insertions(+), 66 deletions(-)
